// Generated by CoffeeScript 1.6.3
(function() {
  var createSelection, create_note, getNode, getNodePath, hight_selection, socket;

  console.log("running webnote extension 0.0.1");

  socket = io.connect('http://localhost:8000');

  socket.on('connect', function() {
    socket.emit('url', location.href);
    socket.on('select', function(selection) {
      return hight_selection(selection);
    });
    socket.on('note.create', function(selection, uuid) {
      return create_note(selection, uuid);
    });
    socket.on('note.edit', function(text, id) {
      $("#" + id).text(text);
      return $("#" + id).attr('contenteditable', 'true');
    });
    return socket.on('note.lock', function(id) {
      return $("#" + id).attr('contenteditable', 'false');
    });
  });

  $(document).ready(function() {
    var tool_bar;
    tool_bar = '<div class="sh-toolbar">\n  <button id="hightlight-trigger" class="sh-btn" data-triggered="false">Hight Light</button>\n  <button id="note-trigger" class="sh-btn" data-triggered="false">Note</button>\n</div>';
    $(tool_bar).appendTo('body');
    $(document).on('click', '.sh-btn', function(e) {
      e.preventDefault();
      if ($(this).attr('data-triggered') === 'true') {
        return $(this).attr('data-triggered', 'false');
      } else {
        $('.sh-btn').attr('data-triggered', 'false');
        return $(this).attr('data-triggered', 'true');
      }
    });
    $(document).on('mouseup', function(e) {
      var s, selection;
      if ($('#hightlight-trigger').attr('data-triggered') === 'true') {
        selection = getSelection();
        if (selection.type === 'Range') {
          s = createSelection(selection);
          if (selection.removeAllRanges) {
            selection.removeAllRanges();
          }
          socket.emit('select', s);
        }
        return;
      }
      if ($('#note-trigger').attr('data-triggered') === 'true') {
        selection = getSelection();
        if (selection.type === 'Caret' || selection.type === 'Range') {
          s = createSelection(selection);
          if (selection.removeAllRanges) {
            selection.removeAllRanges();
          }
          socket.emit('note.create', s);
        }
      }
    });
    $(document).on('focusin', '.sh-note', function(e) {
      var id;
      id = $(this).attr('id');
      return socket.emit('note.lock', id);
    });
    return $(document).on('focusout', '.sh-note', function(e) {
      var id, text;
      id = $(this).attr('id');
      text = $(this).text();
      return socket.emit('note.edit', text, id);
    });
  });

  createSelection = function(selection) {
    var n1, n2, ns;
    n1 = getNodePath(selection.baseNode);
    n2 = getNodePath(selection.extentNode);
    ns = {};
    ns.base_node = n1 > n2 ? n2 : n1;
    ns.base_offset = n1 > n2 ? selection.extentOffset : selection.baseOffset;
    ns.extent_node = n1 > n2 ? n1 : n2;
    ns.extent_offset = n1 > n2 ? selection.baseOffset : selection.extentOffset;
    return ns;
  };

  getNodePath = function(node) {
    var path;
    path = [];
    while (node.tagName !== 'BODY') {
      
    for (i = 0; i < node.parentNode.childNodes.length; i++) {
      if (node.parentNode.childNodes[i] === node) {
        path.unshift(i)
        break
      }
    }
    ;
      node = node.parentNode;
    }
    return path;
  };

  getNode = function(path) {
    var index, node, _i, _len;
    node = $('body')[0];
    for (_i = 0, _len = path.length; _i < _len; _i++) {
      index = path[_i];
      node = node.childNodes[index];
    }
    return node;
  };

  create_note = function(selection, uuid) {
    var elmt, l_block, location, node, offset, s1, s2;
    node = getNode(selection.extent_node);
    offset = selection.extent_offset;
    s1 = $(node).text().substring(0, offset);
    s2 = $(node).text().substring(offset);
    l_block = '<span id="sh-lct"></span>';
    $(node).replaceWith(s1 + l_block + s2);
    location = $("#sh-lct").offset();
    $("#sh-lct").remove();
    console.log(location);
    elmt = "<div id=\"" + uuid + "\" class=\"sh-note\" contenteditable=\"true\"></div>";
    $(elmt).css({
      'top': location.top,
      'left': location.left
    }).appendTo('body');
    return $('.sh-btn').attr('data-triggered', 'false');
  };

  hight_selection = function(selection) {
    var base_node, base_offset, extent_node, extent_offset, from, new_node, next_node, s1, s2, s3, tmp_node;
    base_node = getNode(selection.base_node);
    base_offset = selection.base_offset;
    extent_node = getNode(selection.extent_node);
    extent_offset = selection.extent_offset;
    if (base_node === extent_node) {
      s1 = $(base_node).text().substring(0, base_offset);
      s2 = $(base_node).text().substring(base_offset, extent_offset);
      s3 = $(base_node).text().substring(extent_offset);
      new_node = $('<span>').text(s2);
      new_node.addClass('sh-hightlight');
      $(base_node).replaceWith(s1 + new_node[0].outerHTML + s3);
      return;
    }
    tmp_node = base_node;
    if (tmp_node.nextSibling !== null) {
      tmp_node = tmp_node.nextSibling;
      from = 'sibling';
    } else {
      tmp_node = tmp_node.parentNode;
      from = 'child';
    }
    s1 = $(base_node).text().substring(base_offset);
    s2 = $(base_node).text().substring(0, base_offset);
    new_node = $('<span>').text(s1);
    new_node.addClass('sh-hightlight');
    $(base_node).replaceWith(s2 + new_node[0].outerHTML);
    while (tmp_node !== extent_node) {
      if (from !== 'child' && tmp_node.childNodes.length === 0) {
        if (tmp_node.nextSibling !== null) {
          next_node = tmp_node.nextSibling;
          from = 'sibling';
        } else {
          next_node = tmp_node.parentNode;
          from = 'child';
        }
        if (tmp_node.data.trim() !== '') {
          new_node = $('<span>').text(tmp_node.data);
          new_node.addClass('sh-hightlight');
          $(tmp_node).replaceWith(new_node);
        }
        tmp_node = next_node;
        continue;
      }
      if (from !== 'child') {
        from = 'parent';
        tmp_node = tmp_node.childNodes[0];
        continue;
      }
      if (tmp_node.nextSibling !== null) {
        from = 'sibling';
        tmp_node = tmp_node.nextSibling;
        continue;
      }
      from = 'child';
      tmp_node = tmp_node.parentNode;
    }
    s1 = $(extent_node).text().substring(extent_offset);
    s2 = $(extent_node).text().substring(0, extent_offset);
    new_node = $('<span>').text(s2);
    new_node.addClass('sh-hightlight');
    return $(extent_node).replaceWith(new_node[0].outerHTML + s1);
  };

}).call(this);
